export const URL_MAP = {
  tr: {
    home:       '/',
    seo:        '/seo',
    geo:        '/geo',
    icerik:     '/icerik',
    backlink:   '/backlink',
    performans: '/performans',
    hakkimda:   '/hakkimda',
    referanslar:'/referanslar',
    vakalar:    '/vakalar',
    blog:       '/blog',
    rehber:     '/rehber',
    araclar:    '/araclar',
    sss:        '/sss',
    fiyatlandirma:'/fiyatlandirma',
    iletisim:   '/iletisim',
    randevu:    '/randevu',
    hizmetler:  '/hizmetler',
    kaynaklar:  '/kaynaklar',
    seoRehberi: '/seo-rehberi',
    geoRehberi: '/geo-rehberi',
    aiSozluk:   '/ai-sozluk',
  },
  en: {
    home:       '/',
    seo:        '/seo-consulting',
    geo:        '/geo-consulting',
    icerik:     '/content-strategy',
    backlink:   '/backlink-digital-pr',
    performans: '/performance-growth',
    hakkimda:   '/about',
    referanslar:'/testimonials',
    vakalar:    '/case-studies',
    blog:       '/blog',
    rehber:     '/guides',
    araclar:    '/tools',
    sss:        '/faq',
    fiyatlandirma:'/pricing',
    iletisim:   '/contact',
    randevu:    '/book-a-call',
    hizmetler:  '/services',
    kaynaklar:  '/resources',
    seoRehberi: '/seo-guide',
    geoRehberi: '/geo-guide',
    aiSozluk:   '/ai-glossary',
  }
}
